framework: golang
version: "1.2.0"
preRun:
  command:
    - "go get -d ./..."
    - "go mod download"
    - "go get github.com/gomodule/redigo@latest"
    - "go mod vendor"

postMerge:
  pattern:
    - ""
